# Generated by Django 6.0.3 on 2026-04-18 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='centro_educacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='APP.centroeducacional'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='competencias',
            field=models.ManyToManyField(blank=True, related_name='usuarios_competencia', to='APP.competencia'),
        ),
    ]
