# Generated by Django 6.0.3 on 2026-05-08 20:34

import APP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_perfil',
            field=models.CharField(choices=[('admin', 'Admin'), ('estudiante', 'Estudiante'), ('colegio', 'Colegio'), ('empresa', 'Empresa')], default='admin', max_length=20, verbose_name=APP.models.TipoPerfil),
        ),
    ]
