# Generated by Django 6.0.3 on 2026-05-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_alter_notificacion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
