# Generated by Django 6.0.3 on 2026-05-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_remove_usuario_avatar_url_usuario_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
