# Generated by Django 6.0.3 on 2026-05-08 23:57

import APP.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_alter_usuario_centro_educacional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedia',
            name='contenido_educativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimedia', to='APP.contenidoeducativo'),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimedia', to='APP.post'),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='estado_verificacion',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20, null=True, verbose_name=APP.models.EstadoVerificacion),
        ),
    ]
