# Generated by Django 6.0.3 on 2026-05-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_remove_usuario_correo_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
