# Generated by Django 6.0.3 on 2026-05-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='notif_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='notif_mensajes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='notif_practicas',
            field=models.BooleanField(default=True),
        ),
    ]
