# Generated by Django 6.0.3 on 2026-05-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0009_usuario_notif_email_usuario_notif_mensajes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='visibilidad_perfil',
            field=models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado')], default='publico', max_length=20),
        ),
    ]
