# Generated by Django 6.0.3 on 2026-05-07 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0010_usuario_visibilidad_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('centro_educacional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.centroeducacional')),
            ],
        ),
    ]
