# Generated by Django 6.0.3 on 2026-05-07 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0011_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='curso',
        ),
    ]
