# Generated by Django 6.0.3 on 2026-05-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0013_usuario_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='colegios_vinculados',
            field=models.ManyToManyField(blank=True, related_name='empresas_asociadas', to='APP.centroeducacional'),
        ),
    ]
