# Generated by Django 6.0.3 on 2026-05-07 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0014_usuario_colegios_vinculados'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaPractica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('cupos', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicas_recibidas', to='APP.centroeducacional')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
