# Generated by Django 6.0.3 on 2026-05-07 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0015_ofertapractica'),
    ]

    operations = [
        migrations.AddField(
            model_name='centroeducacional',
            name='especialidades',
            field=models.ManyToManyField(blank=True, related_name='colegios_que_la_imparten', to='APP.competencia'),
        ),
        migrations.CreateModel(
            name='ContenidoEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('url_video', models.URLField(blank=True, help_text='Enlace de YouTube o Vimeo', null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='recursos_educativos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_educativo', to='APP.centroeducacional')),
            ],
        ),
    ]
