# Generated by Django 6.0.3 on 2026-05-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0016_centroeducacional_especialidades_contenidoeducativo'),
    ]

    operations = [
    ]
