# Generated by Django 6.0.3 on 2026-05-08 18:36

import APP.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0017_auto_20260507_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_habilidad', models.CharField(choices=[('tecnica', 'Técnica'), ('interpersonal', 'Interpersonal')], max_length=15, null=True, verbose_name=APP.models.TipoHabilidad)),
                ('habilidad', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='estado_oferta',
            field=models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('expirada', 'Expirada')], max_length=20, null=True, verbose_name=APP.models.EstadoOferta),
        ),
        migrations.AlterField(
            model_name='conexion',
            name='estado_solicitud',
            field=models.CharField(choices=[('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('pendiente', 'Pendiente')], max_length=20, null=True, verbose_name=APP.models.EstadoSolicitud),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='estado_solicitud',
            field=models.CharField(choices=[('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('pendiente', 'Pendiente')], max_length=20, null=True, verbose_name=APP.models.EstadoSolicitud),
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='estado_verificacion',
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='estado_verificacion',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('pendiente', 'Pendiente')], max_length=20, null=True, verbose_name=APP.models.EstadoVerificacion),
        ),
        migrations.RemoveField(
            model_name='ofertapractica',
            name='colegio',
        ),
        migrations.RemoveField(
            model_name='ofertapractica',
            name='empresa',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_perfil',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('colegio', 'Colegio'), ('empresa', 'Empresa')], default='estudiante', max_length=20, verbose_name=APP.models.TipoPerfil),
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='fecha_expiracion',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='fecha_obtencion',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='url',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='contenidoeducativo',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='ofertalaboral',
            name='requisitos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='avatar',
        ),
        migrations.AddField(
            model_name='comentario',
            name='mensaje',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contenidoeducativo',
            name='archivo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='es_practica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ofertalaboral',
            name='colegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practicas_recibidas', to='APP.centroeducacional'),
        ),
        migrations.AddField(
            model_name='ofertalaboral',
            name='competencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='APP.competencia'),
        ),
        migrations.AddField(
            model_name='ofertalaboral',
            name='es_practica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ofertalaboral',
            name='estado_verificacion',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('pendiente', 'Pendiente')], max_length=20, null=True, verbose_name=APP.models.EstadoVerificacion),
        ),
        migrations.AddField(
            model_name='ofertalaboral',
            name='requisitos_competencia',
            field=models.ManyToManyField(blank=True, related_name='ofertas_relacionadas', to='APP.competencia'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='tipo_competencia',
            field=models.CharField(choices=[('especialidad', 'Especialidad'), ('oficio', 'Oficio')], max_length=15, null=True, verbose_name=APP.models.TipoCompetencia),
        ),
        migrations.AlterField(
            model_name='post',
            name='mensaje',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='centro_educacional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APP.centroeducacional'),
        ),
        migrations.CreateModel(
            name='CompetenciaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('estado_verificacion', models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('pendiente', 'Pendiente')], max_length=20, null=True, verbose_name=APP.models.EstadoVerificacion)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.competencia')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='competencias',
            field=models.ManyToManyField(blank=True, related_name='usuarios_competencia', through='APP.CompetenciaEstudiante', to='APP.competencia'),
        ),
        migrations.AddField(
            model_name='ofertalaboral',
            name='requisitos_habilidad',
            field=models.ManyToManyField(blank=True, related_name='ofertas', to='APP.habilidad'),
        ),
        migrations.CreateModel(
            name='HabilidadUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(max_length=100)),
                ('estado_verificacion', models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('pendiente', 'Pendiente')], max_length=20, null=True, verbose_name=APP.models.EstadoVerificacion)),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.habilidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ObtencionCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtencion', models.DateField()),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('estado_verificacion', models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('pendiente', 'Pendiente')], max_length=20, null=True, verbose_name=APP.models.EstadoVerificacion)),
                ('certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.certificado')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados_obtenidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioComentarioLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.comentario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='likes',
            field=models.ManyToManyField(related_name='liked_comments', through='APP.UsuarioComentarioLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='EstadoOferta',
        ),
        migrations.DeleteModel(
            name='EstadoSolicitud',
        ),
        migrations.DeleteModel(
            name='EstadoVerificacion',
        ),
        migrations.DeleteModel(
            name='OfertaPractica',
        ),
        migrations.DeleteModel(
            name='TipoPerfil',
        ),
    ]
